pipeline:

  build:
    image: ubuntu:16.04
    commands:
      - ./test.sh

  poke-jenkins:
    image: appleboy/drone-jenkins
    secrets: [
      jenkins_url,
      jenkins_user,
      jenkins_token,
      jenkins_job
    ]
