pipeline:

  build:
    image: ubuntu:16.04
    commands:
      - ./test.sh

  poke-jenkins:
    image: appleboy/drone-jenkins
    url: ${JENKINS_HOST}
    user: ${JENKINS_USER}
    token: ${JENKINS_TOKEN}
    job: some-job
    secrets: [ jenkins_host, jenkins_user, jenkins_token ]
